# Generated by Django 6.0.7 on 2026-09-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperPortalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_home', 'Can view Home'), ('view_developer_info', 'Can view Developer Info'), ('view_guess_number', 'Can view Guess the Number'), ('view_password_analyzer', 'Can view Password Analyzer')],
                'managed': False,
            },
        ),
    ]
