# Generated by Django 6.0.7 on 2026-09-17 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('has_page', models.BooleanField(default=False)),
                ('requires_permission', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='devs.portalmenu')),
            ],
            options={
                'db_table': 'portal_menu',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='DeveloperPortalPermission',
        ),
    ]
